Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,6 +19,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: test cherry-pick pr
+      id: cherry-pick
       run: |
         git clone https://github.com/open-vela/test.git
         cd test
@@ -27,7 +28,7 @@ jobs:
         git config --global user.name "openvela-robot"
         git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
         echo "git cherry-pick -x pr-branch"
-        cp_pr_result=$(git cherry-pick -x pr-branch 2>&1)
+        cp_pr_result=$(git cherry-pick -x pr-branch 2>&1 || echo "Command failed with error")
         cp_pr_code=$?
         echo $cp_pr_result
         safe_cp_pr_result=$(echo "$cp_pr_result" | tr -d '\n' | tr -d '\r' | sed 's/[]\$`"\\]//g') # 格式化结果
@@ -37,6 +38,7 @@ jobs:
 
     - name: check cherry pick pr result
       run: |
+        echo "${{ steps.cherry-pick.outcome }}"
         if [ ${{ env.CP_PR_CODE }} == 0 ]; then
           echo "cherry pick PR success and continue."
           exit 0
