Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,7 +94,7 @@ jobs:
           if [ -d $REPO_PATH ]; then
             cd $REPO_PATH
             git fetch openvela pull/${{ github.event.pull_request.number }}/head:pr-branch
-            git checkout pr-branch
+            git cherry-pick -x pr_branch
             cd -
           fi
         fi
@@ -139,40 +139,40 @@ jobs:
 #          ghcr.io/open-vela/openvela-ci-linux:latest \
 #          /bin/bash -c "./build.sh vendor/openvela/boards/vela/configs/goldfish-armeabi-v7a-ap-citest -e -Werror -j8"
 
-    - name: Run autotest tasks inside Docker container
-      run: |
-        docker run --rm \
-          -v ${{ github.workspace }}:/workspace \
-          -w /workspace \
-          ghcr.io/open-vela/openvela-ci-linux:latest \
-          /bin/bash -c "cd tests/scripts/script && pytest -m 'common' ./ -B goldfish-armeabi-v7a-ap -L /workspace -P /workspace -F /tmp -R qemu -v --disable-warnings --count=1 --json=/workspace/autotest.json"
+#    - name: Run autotest tasks inside Docker container
+#      run: |
+#        docker run --rm \
+#          -v ${{ github.workspace }}:/workspace \
+#          -w /workspace \
+#          ghcr.io/open-vela/openvela-ci-linux:latest \
+#          /bin/bash -c "cd tests/scripts/script && pytest -m 'common' ./ -B goldfish-armeabi-v7a-ap -L /workspace -P /workspace -F /tmp -R qemu -v --disable-warnings --count=1 --json=/workspace/autotest.json"
 
-    - name: Check autotest result
-      id: autotest_result
-      run: |
-        cd ${{ github.workspace }}
-        mkdir output
-        cp nuttx/nuttx ./*.log ./autotest.json output
-        failed=$(cat autotest.json | jq '.report.summary.failed')
-        if [ "$failed" != "null" ] && [ "$failed" != "0" ]; then
-          echo "autotest failed: $failed"
-          result="failed"
-        else
-          echo "autotest passed"
-          result="success"
-        fi
-        echo "::set-output name=AUTOTEST_RESULT::${result}"
+#    - name: Check autotest result
+#      id: autotest_result
+#      run: |
+#        cd ${{ github.workspace }}
+#        mkdir output
+#        cp nuttx/nuttx ./*.log ./autotest.json output
+#        failed=$(cat autotest.json | jq '.report.summary.failed')
+#        if [ "$failed" != "null" ] && [ "$failed" != "0" ]; then
+#          echo "autotest failed: $failed"
+#          result="failed"
+#        else
+#          echo "autotest passed"
+#          result="success"
+#        fi
+#        echo "::set-output name=AUTOTEST_RESULT::${result}"
 
-    - name: Upload Artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: goldfish-armeabi-v7a-ap-citest_${{ env.REPO_NAME }}-${{ github.event.pull_request.number }}
-        path: output/
+#    - name: Upload Artifact
+#      uses: actions/upload-artifact@v3
+#      with:
+#        name: goldfish-armeabi-v7a-ap-citest_${{ env.REPO_NAME }}-${{ github.event.pull_request.number }}
+#        path: output/
 
-    - name: Exit with autotest exit code
-      run: |
-        if [ ${{ steps.autotest_result.outputs.AUTOTEST_RESULT }} == "success" ]; then
-          exit 0
-        else
-          exit 1
-        fi
+#    - name: Exit with autotest exit code
+#      run: |
+#        if [ ${{ steps.autotest_result.outputs.AUTOTEST_RESULT }} == "success" ]; then
+#          exit 0
+#        else
+#          exit 1
+#        fi
